name: Sync Data to Cloudflare KV

on:
  workflow_run:
    workflows: ["crawl"]
    types:
      - completed
  workflow_dispatch: # 保留手动触发按钮，方便调试

jobs:
  upload:
    runs-on: ubuntu-latest
    # 只有当前置爬虫任务成功时才运行
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Cloudflare KV
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          packageManager: npm
          command: |
            kv:key put --binding=HOK_DATA "hero_list" --path=data/hero/list.json
            kv:key put --binding=HOK_DATA "item_list" --path=data/item/list.json
            kv:key put --binding=HOK_DATA "summoner_list" --path=data/summoner/list.json
            kv:key put --binding=HOK_DATA "hero_images" --path=data/hero_images.json
            kv:key put --binding=HOK_DATA "item_images" --path=data/item_images.json
            kv:key put --binding=HOK_DATA "summoner_images" --path=data/summoner_images.json
